# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get previous workflow status
      uses: Mercymeilya/last-workflow-status@v0.3.2
      id: last_status
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get slack message
      id: slack_message1
      if: ${{ job.status }} == 'failure'
      run: echo "SLACK_MESSAGE=Build failed" >> $GITHUB_ENV

    - name: Print slack message
      run: echo $SLACK_MESSAGE

    - name: Get slack message if recovered
      id: slack_message
      if: ${{ steps.last_status.outputs.last_status }} == 'failure' && ${{ job.status }} == 'success' 
      run: echo "SLACK_MESSAGE=Recovered Build" >> $GITHUB_ENV

    - name: Print slack message Recovered
      run: echo $SLACK_MESSAGE
  

    - name: Build fi
      if: ${{ always() }} &&
        contains('
          refs/heads/main
        ', github.ref) && ${{ job.status }} == 'success' && ${{ steps.last_status.outputs.last_status }} == 'failure'

      run: |
        echo ${{ steps.last_status.outputs.last_status }}

    - name: Build fixed slack message
      uses: gdcorp-action-public-forks/action-slack-notifY@v2
      if:
        contains('
          refs/heads/main
        ', github.ref) && contains('
          refs/heads/main
        ', github.ref)

      env:
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
        SLACK_MESSAGE: 'Style check fixed now!'

