# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  create_env:
    name: testing
    runs-on: ubuntu-latest
    if: ${{ always() }} && ${{ steps.last_status.outputs.last_status }} == 'success'

    steps:
    - uses: actions/checkout@v3
    - name: Get previous workflow status
      run: echo ${{ job.status }}
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get previous workflow status
      if: ${{ always() }}
      uses: Mercymeilya/last-workflow-status@v0.3.2
      id: last_status
      with:
        github_token: ${{ secrets.GITHUB_TOKENs }}
    
    - name: Print previous workflow status
      if: ${{ always() }}
      run: echo ${{ steps.last_status.outputs.last_status }}

    - name: Print current workflow status
      if: ${{ always() }}
      run: echo ${{ job.status }}

    - name: Get slack message
      if: ${{ always() }} && ${{ job.status }} == 'failure'
      id: slack_message1
      run: echo "SLACK_MESSAGE=Build failed" >> $GITHUB_ENV

    - name: Print slack message
      if: ${{ always() }}
      run: echo $SLACK_MESSAGE

    - name: Get slack message if recovered
      id: slack_message
      if: ${{ always() }} && ${{ steps.last_status.outputs.last_status }} == 'failure' && ${{ job.status }} == 'success' 
      run: echo "SLACK_MESSAGE=Recovered Build" >> $GITHUB_ENV

    - name: Print slack message Recovered
      run: echo $SLACK_MESSAGE

    - name: Send slack message to dev branch when build failed
      if: ${{ always() }} &&
        contains('
          refs/heads/main
        ', github.ref) && ${{ job.status }} == 'failure'
      run: echo "slack message $SLACK_MESSAGE"

    - name: Send slack message to dev branch when recovered build
      if: ${{ always() }} &&
        contains('
          refs/heads/main
        ', github.ref) && ${{ steps.last_status.outputs.last_status }} == 'failure' && ${{ job.status }} == 'success' 
      run: echo "slack message $SLACK_MESSAGE"

