on:
  workflow_call:
   inputs:
      ENVIRONMENT:
        description: AWS environment where it sends a Slack notification.
        type: string
name: Slack Notification
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    #environment: dev-private
    steps:
    - name: Send slack message for Recovered Job
      uses: gdcorp-action-public-forks/action-slack-notifY@v2
      if:
        ${{ contains('
          refs/heads/feature/FINTECH-1623
        ', github.ref) }} && ${{ job.status == 'success' }} && $last_status == 'failure'

      env:
        SLACK_WEBHOOK: "dfg"
        SLACK_MESSAGE: Build Recovered
      continue-on-error: true
#
    - name: Get branch name
      shell: bash
      run: |
        if [[ ${GITHUB_EVENT_NAME} == "pull_request" ]]
        then
           echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
           echo "Branch name: ${GITHUB_HEAD_REF}"
        else
           echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
           echo "Branch name: ${GITHUB_REF#refs/heads/}"        
        fi

    - name: Run id
      run: echo ${{ github.run_id }}
    
    - name: Get workflow id
      shell: bash
      run: |
        WORKFLOW_ID=$(curl --header 'authorization: Bearer ${{ github.token }}' \
                           --header 'content-type: application/json' \
        ${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r .workflow_id)
        echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_ENV
        echo "Workflow id: ${WORKFLOW_ID}"

    - name: Get previous build status
      shell: bash
      id: last_status
      run: |
        last_status=$(curl --silent --header 'authorization: Bearer ${{ github.token }}' \
                                    --header 'content-type: application/json' \
        "${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows/${{ env.WORKFLOW_ID }}/runs?per_page=1&status=completed&branch=${{ env.BRANCH_NAME }}" \
        | jq -r .workflow_runs[0].conclusion)
        echo "::set-output name=last_status::$last_status"
        echo "Status of the previous build: $last_status"
    
    - name: print last build status
      run: echo ${{ steps.last_status.outputs.last_status }}
#
    - name: Send slack message for Recovered Job
      uses: gdcorp-action-public-forks/action-slack-notifY@v2
      if:
        ${{ contains('
          refs/heads/feature/FINTECH-1623
        ', github.ref) }} && ${{ job.status == 'success' }} && $last_status == 'failure'

      env:
        SLACK_WEBHOOK: "dfg"
        SLACK_MESSAGE: Build Recovered
#
    - name: Print slack message failure
      if: ${{ always() }}
      run: echo ${{ job.status == 'failure' }}

    - name: Send slack message for Failure Job
      uses: gdcorp-action-public-forks/action-slack-notifY@v2
      if: ${{ always() }} &&
        ${{ job.status == 'failure' }}

      env:
        SLACK_WEBHOOK: "werfg"
        SLACK_MESSAGE: Build Failed
    - name: Print slack message failure
      run: echo ${{ job.status }}
