# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build fixed slack message
      uses: gdcorp-action-public-forks/action-slack-notifY@v2
      if:
        contains('
          refs/heads/main
        ', github.ref) && contains('
          refs/heads/main
        ', github.ref)

      env:
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
        SLACK_MESSAGE: 'Style check fixed now!'

    - name: Build fi
      if: ${{ always() }} &&
        contains('
          refs/heads/main
        ', github.ref)

      run: |
        echo ${{ job.status }}

