# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Slack Notification
    runs-on: ubuntu-latest
    #environment: dev-private
    steps:
    - name: Get previous workflow status
      uses: Mercymeilya/last-workflow-status@v0.3.2
      id: last_status
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build fixed slack message
      if: ${{ success() && steps.last_status.outputs.last_status == 'failure' }}
      run: echo "Success"
    
