# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Slack Notification
    runs-on: ubuntu-latest
    #environment: dev-private
    steps:
    - name: Get latest workflow run status
      uses: actions/github-script@v3
      id: latest-workflow-status
      with:
        script: |
          const runs = await github.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'python-app.yml',
            per_page: 2
          })
          return runs.data.workflow_runs[1].conclusion
        result-encoding: string
    
    - name: Send mail if previous workflow run failed and the current succeeded
      run: echo ${{ success() }}
    - name: test
      run: ${{ steps.latest-workflow-status.outputs.result }}
    
