# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get previous workflow status
      uses: Mercymeilya/last-workflow-status@v0.3.2
      id: last_status
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build fi
      if: ${{ always() }} &&
        contains('
          refs/heads/main
        ', github.ref) && ${{ job.status }} == 'failure'

      run: |
        echo ${{ steps.last_status.outputs.last_status }}

